IF DB_ID(N'PanaderiaPasteleria') IS NULL
BEGIN
  CREATE DATABASE PanaderiaPasteleria;
END;
GO

USE PanaderiaPasteleria;
GO

IF OBJECT_ID(N'dbo.OrderItems', N'U') IS NOT NULL DROP TABLE dbo.OrderItems;
IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL DROP TABLE dbo.Orders;
IF OBJECT_ID(N'dbo.Customers', N'U') IS NOT NULL DROP TABLE dbo.Customers;
IF OBJECT_ID(N'dbo.Products', N'U') IS NOT NULL DROP TABLE dbo.Products;
IF OBJECT_ID(N'dbo.AdminUsers', N'U') IS NOT NULL DROP TABLE dbo.AdminUsers;
GO

CREATE TABLE dbo.Products (
  ProductId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  Description NVARCHAR(500) NOT NULL,
  Category NVARCHAR(80) NOT NULL,
  Price DECIMAL(10,2) NOT NULL CONSTRAINT CK_Products_Price CHECK (Price >= 0),
  ImageUrl NVARCHAR(MAX) NOT NULL,
  Stock INT NOT NULL CONSTRAINT DF_Products_Stock DEFAULT 0 CONSTRAINT CK_Products_Stock CHECK (Stock >= 0),
  IsAvailable BIT NOT NULL CONSTRAINT DF_Products_IsAvailable DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Products_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Products_UpdatedAt DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE dbo.Customers (
  CustomerId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Customers PRIMARY KEY,
  FullName NVARCHAR(160) NOT NULL,
  Dni NVARCHAR(12) NOT NULL,
  Phone NVARCHAR(30) NULL,
  Email NVARCHAR(160) NULL,
  DeliveryAddress NVARCHAR(260) NOT NULL,
  District NVARCHAR(120) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Customers_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO

CREATE INDEX IX_Customers_Dni ON dbo.Customers (Dni);
GO

CREATE TABLE dbo.Orders (
  OrderId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Orders PRIMARY KEY,
  OrderCode NVARCHAR(30) NOT NULL,
  CustomerId INT NOT NULL,
  OrderType NVARCHAR(20) NOT NULL CONSTRAINT CK_Orders_OrderType CHECK (OrderType IN (N'PEDIDO', N'RESERVA')),
  Status NVARCHAR(30) NOT NULL CONSTRAINT DF_Orders_Status DEFAULT N'RECIBIDO'
    CONSTRAINT CK_Orders_Status CHECK (Status IN (N'RECIBIDO', N'CONFIRMADO', N'EN_PREPARACION', N'LISTO', N'EN_CAMINO', N'ENTREGADO', N'CANCELADO')),
  FulfillmentDate DATETIME2 NULL,
  TotalAmount DECIMAL(10,2) NOT NULL CONSTRAINT CK_Orders_Total CHECK (TotalAmount >= 0),
  Notes NVARCHAR(600) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Orders_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Orders_UpdatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_Orders_OrderCode UNIQUE (OrderCode),
  CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerId) REFERENCES dbo.Customers(CustomerId)
);
GO

CREATE INDEX IX_Orders_Status_CreatedAt ON dbo.Orders (Status, CreatedAt DESC);
GO

CREATE TABLE dbo.OrderItems (
  OrderItemId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_OrderItems PRIMARY KEY,
  OrderId INT NOT NULL,
  ProductId INT NOT NULL,
  ProductNameSnapshot NVARCHAR(120) NOT NULL,
  UnitPriceSnapshot DECIMAL(10,2) NOT NULL,
  Quantity INT NOT NULL CONSTRAINT CK_OrderItems_Quantity CHECK (Quantity > 0),
  LineTotal DECIMAL(10,2) NOT NULL CONSTRAINT CK_OrderItems_LineTotal CHECK (LineTotal >= 0),
  CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES dbo.Orders(OrderId),
  CONSTRAINT FK_OrderItems_Products FOREIGN KEY (ProductId) REFERENCES dbo.Products(ProductId)
);
GO

CREATE TABLE dbo.AdminUsers (
  AdminUserId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AdminUsers PRIMARY KEY,
  Username NVARCHAR(80) NOT NULL,
  PasswordHash NVARCHAR(256) NOT NULL,
  PasswordSalt NVARCHAR(128) NOT NULL,
  Role NVARCHAR(40) NOT NULL CONSTRAINT DF_AdminUsers_Role DEFAULT N'ADMIN',
  IsActive BIT NOT NULL CONSTRAINT DF_AdminUsers_IsActive DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_AdminUsers_CreatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_AdminUsers_Username UNIQUE (Username)
);
GO
